---
- name: grafana | check vars are defined
  assert:
    that:
      - grafana_admin_password is defined
      - grafana_auth_anonymous_org_role is defined
      - grafana_auth_anonymous_org_name is defined
      - grafana_domain is defined
  tags: ['docker_grafana']

- include_tasks: base.yml
  tags: ['docker_grafana']

- name: grafana | create docker volume data
  docker_volume:
    name: grafana__var_lib_grafana
  tags: ['docker_grafana']

- name: grafana | create provisioning dashboards docker volume
  docker_volume:
    name: grafana__etc_grafana_provisioning_dashboards
  tags: ['docker_grafana']

- name: grafana | create provisioning datasources docker volume
  docker_volume:
    name: grafana__etc_grafana_provisioning_datasources
  tags: ['docker_grafana']
