---
- name: update APT Cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: pre-requirements install
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
      - gnupg2
    state: present
