---
- name: traefik-restart
  systemd:
    name: docker-compose@traefik
    state: restarted
  tags: ['docker_traefik']

- name: watchtower-restart
  systemd:
    name: docker-compose@watchtower
    state: restarted
  tags: ['docker_watchtower']

- name: grafana-restart
  systemd:
    name: docker-compose@grafana
    state: restarted
  tags: ['docker_grafana']
